In [25]:
import pandas as pd
import difflib
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
def load_data():
    user_game_df = pd.read_csv("raw_data/rawg_user_games.csv")
    return user_game_df

In [58]:
def get_ratings(df):
    filter_df = df[df['user_rating']>0]
    ratings_df = filter_df[['user_id','game_id','user_rating']]
    return ratings_df

In [59]:
data = load_data()
rating_df = get_ratings(data)

In [60]:
rating_df

user_id  game_id  user_rating
0             1   446900            4
1             1   264830            5
2             1    58443            4
4             1    21889            4
5             1     1190            4
...         ...      ...          ...
254743      997     5286            3
254744      997     3328            4
254745      997     4200            5
254746      997     3498            4
255047      998     1447            4

[24378 rows x 3 columns]

In [61]:
rating_df[rating_df['game_id'] == 256]

Empty DataFrame
Columns: [user_id, game_id, user_rating]
Index: []

In [62]:
rating_df.head(20)

user_id  game_id  user_rating
0         1   446900            4
1         1   264830            5
2         1    58443            4
4         1    21889            4
5         1     1190            4
6         1     1175            4
7         1   326668            5
9         1   262668            4
10        1    59052            4
11        1    58156            3
12        1     6630            5
13        1     1972            4
15        1    58940            4
16        1     6111            4
17        1    33613            4
19        1     1867            4
20        1     1353            4
22        1   359798            4
23        1     6675            4
24        1     6370            4

In [63]:
aa = rating_df[rating_df['user_id'] == 24]
aa

user_id  game_id  user_rating
3616       24    10646            4
3626       24    19279            5
3627       24    18099            3
3679       24    19495            4
3701       24   264828            3
3725       24    11593            5
3734       24    21371            4
3742       24    19442            4
3769       24    51487            4
3790       24     2536            4
3798       24      284            5
3802       24     3955            4
3831       24    59637            3
3839       24    19458            5
3877       24     2830            4
3947       24     1682            3
3956       24     4223            3
3963       24       39            3
3988       24     2454            5

In [64]:
aa = aa[['game_id', 'user_rating']]
aa

game_id  user_rating
3616    10646            4
3626    19279            5
3627    18099            3
3679    19495            4
3701   264828            3
3725    11593            5
3734    21371            4
3742    19442            4
3769    51487            4
3790     2536            4
3798      284            5
3802     3955            4
3831    59637            3
3839    19458            5
3877     2830            4
3947     1682            3
3956     4223            3
3963       39            3
3988     2454            5

In [65]:
aa_dict = aa.to_dict("records")
aa_dict

[{'game_id': 10646, 'user_rating': 4},
 {'game_id': 19279, 'user_rating': 5},
 {'game_id': 18099, 'user_rating': 3},
 {'game_id': 19495, 'user_rating': 4},
 {'game_id': 264828, 'user_rating': 3},
 {'game_id': 11593, 'user_rating': 5},
 {'game_id': 21371, 'user_rating': 4},
 {'game_id': 19442, 'user_rating': 4},
 {'game_id': 51487, 'user_rating': 4},
 {'game_id': 2536, 'user_rating': 4},
 {'game_id': 284, 'user_rating': 5},
 {'game_id': 3955, 'user_rating': 4},
 {'game_id': 59637, 'user_rating': 3},
 {'game_id': 19458, 'user_rating': 5},
 {'game_id': 2830, 'user_rating': 4},
 {'game_id': 1682, 'user_rating': 3},
 {'game_id': 4223, 'user_rating': 3},
 {'game_id': 39, 'user_rating': 3},
 {'game_id': 2454, 'user_rating': 5}]

In [66]:
def transform_df(df):
    game_matrix_df = df.pivot(index = 'user_id', columns ='game_id', values = 'user_rating').fillna(0)
    return game_matrix_df

In [68]:
rating_matrix = transform_df(rating_df)

In [69]:
rating_matrix.head(25)

game_id  20      21      22      24      25      26      27      28      \
user_id                                                                   
1           0.0     0.0     0.0     3.0     0.0     0.0     4.0     0.0   
2           0.0     0.0     0.0     4.0     0.0     0.0     0.0     5.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8           3.0     0.0     0.0     0.0     0.0     0.0     0.0     5.0   
9           0.0     0.0     0.0     0.0     0.0     4.0     0.0     5.0   
11          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
12          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
15          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
24          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
25          0.0     0.0     0.0     0.0     5.0     0.0     0.0     5.0   
26          0.0     0.0     0.0     0.0     0.0     0.0     0.0     3.0   
27          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
30          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
31          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
35          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
37          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
39          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
42          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
45          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
49          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
53          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
54          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56          0.0     0.0     0.0     5.0     0.0     0.0     0.0     4.0   
61          0.0     0.0     0.0     0.0     0.0     0.0     0.0     5.0   
64          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

game_id  29      30      ...  446900  447797  452634  452646  457729  461649  \
user_id                  ...                                                   
1           0.0     0.0  ...     4.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     3.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
8           0.0     0.0  ...     0.0     0.0     5.0     0.0     0.0     0.0   
9           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
11          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
12          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
15          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
24          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
25          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
26          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
27          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
30          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
31          5.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
35          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
37          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
39          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
42          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
45          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
49          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
53          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
54          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
56          0.0     0.0  ...     0.0     0.0     0.0  

In [70]:
u_id = rating_matrix.index

In [71]:
u_id[0]

1

In [72]:
rating_matrix.shape

(236, 5592)

In [73]:
game_id_matrix = rating_matrix.columns

In [74]:
game_id_matrix

Int64Index([    20,     21,     22,     24,     25,     26,     27,     28,
                29,     30,
            ...
            446900, 447797, 452634, 452646, 457729, 461649, 463727, 484913,
            491003, 527389],
           dtype='int64', name='game_id', length=5592)

In [75]:
real_sample = rating_matrix.iloc[1].values
real_sample

array([0., 0., 0., ..., 0., 0., 0.])

In [76]:
new_user = [
    { 
        "game_id": 26,
        "user_rating": 4 
    },
    { 
        "game_id": 28,
        "user_rating": 5 
    },
    { 
        "game_id": 256,
        "user_rating": 0 
    }
    ]

In [77]:
X_matrix = pd.DataFrame(game_id_matrix)

In [78]:
X_matrix.shape

(5592, 1)

In [79]:
X_matrix['ratings'] = 0

In [80]:
X_matrix = X_matrix.set_index('game_id')

In [81]:
X_matrix.shape

(5592, 1)

In [82]:
256 in X_matrix.index

False

In [83]:
new_user[0]["user_rating"]

4

In [84]:
new_user

[{'game_id': 26, 'user_rating': 4},
 {'game_id': 28, 'user_rating': 5},
 {'game_id': 256, 'user_rating': 0}]

In [85]:
for game in aa_dict:
    game_id = game["game_id"]
    ratings = game["user_rating"]
    if game_id in X_matrix.index:
        X_matrix.loc[game_id,'ratings'] = ratings

In [86]:
X_matrix[X_matrix.index == 430]

ratings
game_id         
430            0

In [87]:
X = X_matrix['ratings'].values

In [88]:
X.shape

(5592,)

In [89]:
X_matrix.shape

(5592, 1)

In [39]:
X

array([0, 0, 0, ..., 0, 0, 0])

## Import preprocessor

In [1]:
import pickle5 as pickle

In [3]:
with open('preproc.pickle', "rb") as input_file:
    neigh = pickle.load(input_file)

In [7]:
preproc_matrix = neigh.get_rating_matrix()

In [8]:
preproc_matrix

game_id  20      21      22      24      25      26      27      28      \
user_id                                                                   
1           0.0     0.0     0.0     3.0     0.0     0.0     4.0     0.0   
2           0.0     0.0     0.0     4.0     0.0     0.0     0.0     5.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8           3.0     0.0     0.0     0.0     0.0     0.0     0.0     5.0   
9           0.0     0.0     0.0     0.0     0.0     4.0     0.0     5.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
984         0.0     0.0     0.0     0.0     0.0     0.0     0.0     5.0   
989         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
995         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
997         0.0     0.0     0.0     0.0     4.0     0.0     5.0     5.0   
998         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

game_id  29      30      ...  446900  447797  452634  452646  457729  461649  \
user_id                  ...                                                   
1           0.0     0.0  ...     4.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     3.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
8           0.0     0.0  ...     0.0     0.0     5.0     0.0     0.0     0.0   
9           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
984         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
989         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
995         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
997         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
998         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

game_id  463727  484913  491003  527389  
user_id                                  
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
8           0.0     0.0     0.0     0.0  
9           0.0     0.0     0.0     0.0  
...         ...     ...     ...     ...  
984         0.0     0.0     0.0     0.0  
989         0.0     0.0     0.0     0.0  
995         0.0     0.0     0.0     0.0  
997         0.0     0.0     0.0     0.0  
998         0.0     0.0     0.0     0.0  

[236 rows x 5592 columns]

In [173]:
! ls ..

Dockerfile                         gl-test-svd-plus.ipynb
MANIFEST.in                        knn_model.pickle
Makefile                           mag_improved_content_b_model.ipynb
Procfile                           notebooks
README.md                          preproc.pickle
Untitled.ipynb                     raw_data
api                                requirements.txt
game_one                           scripts
gl-baseline-baseline.ipynb         setup.py
gl-nmf-test-package.ipynb          setup_project.sh
gl-test-baseline.ipynb             tests
gl-test-package.ipynb


In [94]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
samples = rating_matrix

In [95]:
samples.shape

(236, 5592)

In [96]:
neigh = NearestNeighbors(n_neighbors=1)
neigh.fit(samples)


NearestNeighbors(n_neighbors=1)

In [97]:
X.shape

(5592,)

In [98]:
X

array([0, 0, 0, ..., 0, 0, 0])

In [99]:
y = neigh.kneighbors(X.reshape(-1, 1).transpose(), 1, return_distance=False)

In [100]:
y

array([[8]])

In [101]:
y_index = y[0][0]

In [102]:
y_index

8

In [103]:
y_final = u_id[y_index]

In [104]:
y_final

24

In [51]:
rating_matrix

game_id  20      21      22      24      25      26      27      28      \
user_id                                                                   
1           0.0     0.0     0.0     3.0     0.0     0.0     4.0     0.0   
2           0.0     0.0     0.0     4.0     0.0     0.0     0.0     5.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8           3.0     0.0     0.0     0.0     0.0     0.0     0.0     5.0   
9           0.0     0.0     0.0     0.0     0.0     4.0     0.0     5.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
984         0.0     0.0     0.0     0.0     0.0     0.0     0.0     5.0   
989         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
995         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
997         0.0     0.0     0.0     0.0     4.0     0.0     5.0     5.0   
998         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

game_id  29      30      ...  446900  447797  452634  452646  457729  461649  \
user_id                  ...                                                   
1           0.0     0.0  ...     4.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     3.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
8           0.0     0.0  ...     0.0     0.0     5.0     0.0     0.0     0.0   
9           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
984         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
989         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
995         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
997         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
998         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

game_id  463727  484913  491003  527389  
user_id                                  
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
8           0.0     0.0     0.0     0.0  
9           0.0     0.0     0.0     0.0  
...         ...     ...     ...     ...  
984         0.0     0.0     0.0     0.0  
989         0.0     0.0     0.0     0.0  
995         0.0     0.0     0.0     0.0  
997         0.0     0.0     0.0     0.0  
998         0.0     0.0     0.0     0.0  

[236 rows x 5592 columns]

In [ ]:
#nb de jeu d'un genre spécifique par user